name: EchoLog
version: '${project.version}'
main: org.Axe1l.echolog.EchoLogPlugin
api-version: '1.21'
authors: [axe1l]
description: The ultimate logging plugin.
commands:
  echolog:
    description: EchoLog Einstellungen & Admin-Tools
    usage: /echolog [reload|gui]
    permission: echolog.use
permissions:
  echolog.use:
    default: op
  echolog.view:
    default: true